# CML Lab Builder Configuration
# ================================

# Paths to default device configs and jinja templates
paths:
  conf_files_directory: "./default_configs"
  jinja_directory: "./j2"

# Global flags that control labs-build behavior
flags:
  # If update_existing_lab is set to true, existing labs will be updated to align with the node and links given in the config
  # Any existing cabling will not be deleted. Any existing cabling which aligns with the lab yaml links, will be kept as is and no duplicate links will be created
  # If update_existing_lab is set to false, existing labs will be skipped
  update_existing_lab: true
  # If update_existing_lab is set to true AND delete_existing_nodes is set to true, then the full existing topology and nodes will be deleted and rebuilt fresh
  # If update_existing_lab is set to false, then delete_existing_nodes is ignored
  # Use this option (delete_existing_nodes: true), if you want the lab build exactly as per lab yaml with no extra nodes or extra cabling left over from existing lab
  delete_existing_nodes: true

# List of lab YAML files to build (processed in order)
lab_files:
  # - "./examples/VXLAN_EVPN_LARGE.yml"
  # - "./examples/VXLAN_EVPN_TINY_MULTISITE.yml"
  # - "./examples/BGP_ROUTED_5STAGE.yml"
  # - "./examples/CLASSIC_3TIER.yml"
  - "./VXLAN_EVPN_LARGE_BGL.yml"
